<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>S</string>
   </array>
  <key>name</key>
  <string>fCore_has</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.fCore_has</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\let|const|for\b)</string>
          <key>name</key>
          <string>text.fCore_has</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\ldr|nop|add(i)?|sub(i)?|mul(i)?|ldc|stop|itf|fti|ble|bgt|bne|beq|mov\b)</string>
          <key>name</key>
          <string>text.fCore_has</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>text.fCore_has</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>text.fCore_has</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.fCore_has</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.fCore_has</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.fCore_has</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
  </dict>
</dict>
</plist>
